services:
  api:
    volumes:
      - ./api:/app/api
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ${HF_CACHE_DIR:-~/.cache/huggingface}:/opt/hf
    environment:
      PYTHONUNBUFFERED: "1"
    command:
      - uvicorn
      - api.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload

  worker:
    volumes:
      - ./api:/app/api
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ${HF_CACHE_DIR:-~/.cache/huggingface}:/opt/hf
    environment:
      PYTHONUNBUFFERED: "1"